import "./register/EndNode.js";
import "./register/StartNode.js"
import "./register/TimerNode.js"
import "./register/AddNode.js"
import "./register/SubProcess.js"
import "./register/ApprovalNode.js"
import "./register/Branch.js"
import "./register/NoticeNode.js"
import "./register/Edge.js"